### ISSUE TITLE
478 US Code Design

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#132]
Section 478.103 contains a chunk of the US Code. Currently, we just display each paragraph on its own line, but we should figure out a nicer representation. We can probably leverage our work here if we ever want to pull in US Code for display.

<img width="587" alt="screen shot 2015-11-30 at 11 46 39 am" src="https://cloud.githubusercontent.com/assets/326918/11477919/33baa284-9758-11e5-8243-62c86a70ee63.png">

**Comment by jehlers** [comment]
Here is the notice that needs to be posted via this section of the reg: https://www.atf.gov/file/58806/download

**Comment by jehlers** [comment]
Section 478.103 is meant to give licensees the tools they need to comply with the law. Paragraph (b) lists 4 points and a section of USC that must be given to people who are buying a gun. Paragraph (e) lists 4 points that need to be posted in a facility that sells guns. (This is my very generalized interpretation of these two paragraphs.) 

ATF has taken both of these text snippets and created documents that users can print out and use to comply with this part of the regulation. Or, users can copy and paste the text directly from the regulation and create their own formatted documents. 

Here are a few options for the layout of this section:

#### Option 1 - Minimal formatting

This option is the closest thing to a "manual" option. It closely follows the formatting of the brochure that ATF created and is the formatting I would expect the parser to spit this text out without any additional enhancements. The one new addition to this is external links. If someone were to click on the "ATF I 5300.2" link, they would be taken directly to the PDF in a new tab.

We could pull out the "(x)(1)" numerals in the USC to match the "1." numerals elsewhere in the regulation, but I kept them as is for now to differentiate the USC text from reg text. 

![atf-usc-01a](https://cloud.githubusercontent.com/assets/4267825/12066140/77e2444c-afb0-11e5-9a3e-ada3f244cbdf.png)

#### Option 2 - Gray box

This version follows the pattern the tool is currently using for the USC snippet. Adding this gray box helps to differentiate this text from the reg text, and makes it a little easier to copy and paste (or at least know where the snippet needed starts and ends). 

![atf-usc-01b](https://cloud.githubusercontent.com/assets/4267825/12066237/aecdbcf0-afb2-11e5-85ac-25f2d663a258.png)

#### Option 3 - Curated enhancements

The two versions are slightly different visual designs of essentially the same concept. Since ATF has gone through the effort of making documents that people can use, I wanted to emphasize those documents and help people find them more easily. 

In these two options, I've added a big gray "button" that points out these documents (in addition to the external links within the reg text). Below each button is a box with the text that a user could copy and paste if they want. I've hidden most of the text in an expandable box simply because it is long, and less necessary if the user downloads the PDF. However, if we don't want to collapse this text, both of these options will work with either of the layouts above. 

I've also experimented with adding additional external links. Something like "ATF I 5300.2" could maybe be automated, but we may also want to make something like "ATF Distribution Center" an external link. We can discuss what types of links may be useful inside the reg, or do not need to add any additional links.

**Option 3a**

![atf-usc-01c](https://cloud.githubusercontent.com/assets/4267825/12066273/688fae46-afb3-11e5-97d9-2221dd5666e0.png)

**Option 3b**

![atf-usc-01d](https://cloud.githubusercontent.com/assets/4267825/12066305/a9d63dfc-afb3-11e5-849a-d63e8f281e92.png)

**Comment by jehlers** [comment]
One additional bit of functionality we could potentially add is a copy/paste feature. If we add a link, like the one shown below, the entire text snippet would be copied to the user's clipboard and could be pasted anywhere they wanted. 

<img width="564" alt="screen shot 2015-12-31 at 12 04 39 pm" src="https://cloud.githubusercontent.com/assets/4267825/12066532/3889bf9e-afb7-11e5-8334-2ef3c849aee2.png">
 
or 

<img width="554" alt="screen shot 2015-12-31 at 12 04 27 pm" src="https://cloud.githubusercontent.com/assets/4267825/12066535/44c30ab8-afb7-11e5-94bb-0d7750524af5.png">

I keep going back and forth with this idea because it would be super helpful for someone who is copying this text and creating their own document, but I don't know how large of a use case that is. It also feels a little weird to do something like this just for these two snippets of text and not the rest of the regulation, but this could be a feature we bring to more places in the tool if users find it useful.

**Comment by jehlers** [comment]
From the sprint demo - 

- Going with option 2 for formatting, but also bringing in the PDF button from option 3a before the gray box
- We can also bring in the copy feature

**Comment by jehlers** [comment]
Here is the PDF button, copy link, and chosen formatting all put together: 

![screen shot 2016-01-04 at 2 18 40 pm](https://cloud.githubusercontent.com/assets/4267825/12098118/1c9c2b7a-b2ee-11e5-8981-722ecb58af40.png)

**Comment by cmc333333** [comment]
Implementation details have been split into
* #225 
* #224 
* #223 
* #222
