### ISSUE TITLE
General ATF Branding

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#133]
@jeremiak did a wonderful job making ATF's eregs fit in with www.atf.gov, but he only had a day or two. We should take another run at it.

**Comment by cmc333333** [comment]
@jehlers please make new issues for anything we can implement

**Comment by jehlers** [comment]
My goal for this sprint was to take a look at the current ATF eRegs visual styles to make sure they fit with the general ATF brand, and generally make sure everything looks right. Additionally, we need to clean up the styles in a more systematized way so that there are no leftover CFPB styles in the CSS and the front-end theme becomes easier to manage. This also brings the added benefit of making the process of bringing this tool to other agencies faster in the future.

Overall, I think the tool looks pretty good. The dark blue header and medium blue sub-head help to differentiate this tool, but keep it feeling official and part of the ATF brand. 

#### ATF logo

The first update I’d like to propose is bringing in the ATF logo next to the seal to match what is on the main website. So, instead of using text for ATF:

![screen shot 2015-12-17 at 11 43 41 am](https://cloud.githubusercontent.com/assets/4267825/11879110/5d0219fc-a4c7-11e5-8ae7-916c1721cd5f.png)

it would look like this:

![screen shot 2015-12-17 at 11 43 53 am](https://cloud.githubusercontent.com/assets/4267825/11879114/688be366-a4c7-11e5-96b1-ffd0244c4041.png)

- [ ] Yes?


#### Link colors

The only color missing from ATF’s current color palate is the link color. The site is still using the CFPB pacific blue. We should make sure all links are ATF’s link blue #0062a0.


#### Fonts

eRegulations is all about reading. On the web, people don’t usually read as much text as they would on paper. However, eRegs is the exception to the rule. Optimizing the fonts for the best screen readability is very important. The current ATF fonts are working well on the main website because there are more chances for images and other visuals to break up the text. It is also less important on the main website to read every bit of text. For regulations, however, the only visuals we have to break up the blocks of text are the headings. 

Here are a few of the problems I found with the current fonts Slabo 13px and Works Sans:

- Slabo 13px only comes in 1 weight - I think there are certain places on eRegs right now where we are fake bolding the text. This is a big no-no. Allowing the browser to change the weight of the font actually hurts the font’s legibility. Font weights are made individually and are optimized for the best legibility at those weights. 
- Neither Slabo 13px or Work Sans comes in italic - There are also certain parts of eRegs right now where we are faking italics. The same issues apply with the faking the bold above.
- In order to make eRegs as skimmable as possible, it is important to distinguish the headers from the body text. Keeping the contrast consistent between heading font and body font allows the eye to know what to look for as it scans through the text. Right now, we are using Slabo 13px for the H1 and switching to Work Sans for the lower headings. ATF’s standard headings are all Slabo 13px, but due to the above weight issues, it is harder to differentiate them within the large blocks of text.

Here is what the current hierarchy looks like:

![atf-currenttype](https://cloud.githubusercontent.com/assets/4267825/11879173/c69e63ca-a4c7-11e5-857d-10ea33817578.png)

Here is what I would like to propose:

![atf-newtype](https://cloud.githubusercontent.com/assets/4267825/11879179/d2ffce38-a4c7-11e5-826b-ccd91343fbad.png)

The new hierarchy is based on the current U.S. Web Design Standards and some of their early research, but is adjusted slightly to meet the needs of eRegs as a tool. Both fonts are still free google fonts, but they have been tested a little more than Slabo 13px and Work Sans.

**Merriweather is the serif body text.** Serif fonts are good for large chunks of text because the serifs help the eye flow from one letter to the next. Originally they were not as good for the screen as they are for print but that is no longer the case. Merriweather was specifically designed for on-screen use.

**Lato is the san serif font for the headings.** It is a little bit rounder than Work Sans and also has a larger “x-height” which means that it is legible at all sizes. This is particularly important for the interface around the regulation where the font size can go down to 12px. It also comes in 8 or so different weights. We won’t use all of them, but it will provide for more flexibility.

I’ve tested both of these fonts on a variety of screens with different resolutions. Both fonts perform particularly well on everything from phones to old PC laptops. 

This is a departure from the fonts on the ATF website now, but I don’t think it is too far. The serif and san serif are switched in their rolls which does make it seem like a larger departure than it is. But I do think that this combination gives off the same modern and professional look and feel that the Slabo 13px and Work Sans is doing on the main website. These new fonts also mirror the feeling of the authoritative paper regulations and rulings.

This is what it would look like in place:

![atf-newtype1](https://cloud.githubusercontent.com/assets/4267825/11879237/2da8829e-a4c8-11e5-9f8c-1ba0ad5aa07a.png)

- [ ] Yes?


#### Homepage

Here is what the homepage would look like with the new fonts:

![atf-homepage](https://cloud.githubusercontent.com/assets/4267825/11879249/3dfe9746-a4c8-11e5-9c1d-54343a611565.png)

I’ve also added an ATF footer that would take users back to various parts of the ATF website. Is this something we want? 

Along those same lines, the CFPB has 2 modules in the right sidebar on this page. One is a list of recent FR notices that take users to the FR website. Another is a contact box near the “about eRegulations text. Do we want either of those modules for this homepage?

- [ ] Footer?
- [ ] Recent FR notice links?
- [ ] Contact box?
- [ ] Something else?

**Comment by jehlers** [comment]
After a conversation with Hadiza: 

- We should implement the new logo, link color, and fonts. 
- The footer with links to the website may cause confusion, so I'm going to try a new one with just a "looking for atf.gov" link.
- Still waiting to hear about what we may want to add to the left side of the homepage

cc @Journerdism

**Comment by jehlers** [comment]
Hadiza, what do you think of this footer?

![c](https://cloud.githubusercontent.com/assets/4267825/11958851/44423fda-a898-11e5-96ae-6c2118038c23.png)

**Comment by jehlers** [comment]
Hadiza gave the :+1: on this footer.

**Comment by jehlers** [comment]
@Journerdism I created an issue #192 for the logo. Should we make issues for the other parts of this one and then close it? Some of the font and link color work may fall into the theming work, but I'm not sure how we want to break this up.

cc @theresaanna @jbarnicle

**Comment by jehlers** [comment]
Some of these issues may be related to #191

**Comment by jehlers** [comment]
We are still waiting to hear about more modules on the homepage, but I created issue #218 for the new footer.
