### ISSUE TITLE
27 CFR 447.21 Munitions List

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#185]
Section 21 is a big ol list of information, broken up by some headers. It's currently coming across as a "flat" extract (similar to the problems in #132). What can we do to make this a better experience? To close this issue, let's have an explicit plan. Implementation can come next.

**Comment by jehlers** [comment]
The U.S. Munitions List is published in section 21 of this regulation. Therefore, it should look like all other regulation text. Here is not all of the section (because it's a very long section), but a good amount of it to show how our type hierarchy can apply to this section:

_It is broken into a few different images for easier posting here._ 

![atf-munitionslist-01a](https://cloud.githubusercontent.com/assets/4267825/12068370/f907af66-afd9-11e5-82d1-f6085bd90656.png)

![atf-munitionslist-01b](https://cloud.githubusercontent.com/assets/4267825/12068371/fb8c840a-afd9-11e5-80c1-4348aecf057d.png)

![atf-munitionslist-01c](https://cloud.githubusercontent.com/assets/4267825/12068373/fd960028-afd9-11e5-9ae0-3802cd62446f.png)

![atf-munitionslist-01d](https://cloud.githubusercontent.com/assets/4267825/12068374/ffdd2c6c-afd9-11e5-8459-9b6ba9e30cf3.png)

I haven't found anything out of the ordinary in this section that would warrant a different type of treatment. The only inconsistency I found is that sometimes there is a "Note:", sometimes there are multiple "Note:"s in a row, and sometimes there are "Notes:". I'm not sure what the difference between any of them are, or if there is any difference. Also some are 1-2 sentences, and some have their own outline structure. My current assumption is that they do not need to be treated special either, but I want to look into this a little more.

**Comment by jehlers** [comment]
_One more thought for discussion on Monday._

Since this section is structured more similar to "chapters" where each category has its own outline structure within it (as opposed to the whole section being one outline), should we treat it more like the Appendix in CFPB regulations:

<img width="709" alt="screen shot 2015-12-31 at 4 28 36 pm" src="https://cloud.githubusercontent.com/assets/4267825/12068425/cc7265ca-afdb-11e5-81d5-1da4c158b2d4.png">

Here is a more accurate example of how this section would look, but is harder to take a screenshot: http://www.consumerfinance.gov/eregulations/1005-A/2014-20681#1005-A

We could create an internal table of contents for this list since it is made up of 22 categories. Thoughts?

**Comment by jehlers** [comment]
From the sprint demo today:

- Formatting is good to go, but we want to leave the NOTES as they are currently styled in the tool, gray boxes and smaller text
- We do want to bring in the internal table of context / index. It should go under the title "The U.S. Munitions List" but before the first CATEGORY.

**Comment by jehlers** [comment]
Here is a general idea _(there are a lot more sections that would be listed)_ of how the index would look as discussed in the sprint demo:

![screen shot 2016-01-04 at 1 57 06 pm](https://cloud.githubusercontent.com/assets/4267825/12097725/42cefbf4-b2eb-11e5-875f-de53de5d2a27.png)

**Comment by jehlers** [comment]
And, here is the "new" NOTE styling:

![screen shot 2016-01-04 at 2 04 41 pm](https://cloud.githubusercontent.com/assets/4267825/12098003/3ae60b4c-b2ed-11e5-9cd0-cca751a33d1d.png)

If there is more than one NOTE in a row, they can all live in the same gray box.

**Comment by Journerdism** [comment]
Needs to be broken down
