### ISSUE TITLE
Replace waitress

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#200]
With Gunicorn. Update cloud.gov docs to point to this as a recommendation.

See openFEC for an example.

**Comment by jmcarp** [comment]
@cmc333333 can you remind me why this matters? I dug up some articles on gunicorn vs waitress in the context of heroku (e.g. http://blog.etianen.com/blog/2014/01/19/gunicorn-heroku-django/), but those don't seem relevant to us, since cloud.gov requests get routed through nginx before they reach us. So I'm not sure how much difference the choice between gunicorn / waitress / uwsgi / whatever makes for us.

Funny story--I didn't realize that we were already using nginx last year and set up FEC to run both the nginx and python buildpacks for no reason. Only got around to rolling that back recently :confounded:

**Comment by cmc333333** [comment]
@dlapiduz has cited waitress as a potential cause of random failures we had early on (when we only used one application instance). Further, as of the last poll, gunicorn was better understood on the team. Given that we can swap in gunicorn over waitress relatively easily, it seems like the right choice.

Importantly, we should also update the cloud.gov docs.

**Comment by dlapiduz** [comment]
@cmc333333 @jmcarp do you serve static assets with waitress/gunicorn?

**Comment by jmcarp** [comment]
@cmc333333 can correct me if I'm wrong, but I believe we do.

**Comment by cmc333333** [comment]
Indirectly through `whitenoise`, yep. We basically just followed the cloud.gov instructions
