### ISSUE TITLE
Create more robust landing page example for ATF to react to and enhance

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#227]
As we discussed as small content project, we'd like to figure out how to make the landing pages for each of the ATF regulations more robust, user friendly and contextual. So let's take one of these ATF eReg landing pages and figure out ways to add more information (related links, contact info, etc.) to present to ATF for feedback, enhancements and approval (and then we can knock out the remaining ones to make them a little more user-friendly and less lawyer-y):
https://atf-eregs.18f.gov/

Here's a bunch of examples from CFPB:
http://www.consumerfinance.gov/eregulations/

**Comment by brittag** [comment]
Here's an idea for a more user-centered landing page based on [the current landing part for part 447](https://atf-eregs.18f.gov/447) (I'll explain my thinking after the screenshots). The descriptions of the regulation are examples of the type of language this page could include, rather than being recommendations for specific phrasing.

<img width="945" alt="447 landing page context - part 1" src="https://cloud.githubusercontent.com/assets/391313/12239841/86ad1082-b83f-11e5-9ddf-5ec681907d8a.png">

<img width="932" alt="447 landing page context - part 2" src="https://cloud.githubusercontent.com/assets/391313/12240226/2cc5067c-b841-11e5-8c27-bd6270e3e169.png">

<img width="585" alt="447 landing page context - part 3" src="https://cloud.githubusercontent.com/assets/391313/12239862/9fd87722-b83f-11e5-8f94-bff4cf70b1c9.png">

Things I changed as an experiment in adding more support for the reader:

* I made "We are still in the process of verifying the content of this regulation." much more specific: who is verifying the regulation, why is it being verified, and where is an alternative if the reader wants an already-verified version? I also changed this to a dark yellow color (to indicate "warning") instead of red (which often indicates "error").
* I changed the introduction sentence into a plain language summary instead of a direct quote from the legal text.
* I changed "The Regulation" to "This regulation" to be more direct.
* I made the human-readable list of contents more detailed and specific, and I linked each subject to the part of the regulation that deals with that subject.
* I added a section for "What law does this regulation relate to?" to help readers understand why the regulation exists at a glance.
* I linked to several resources on the ATF website that deal with import and export issues, including the relevant places to ask questions (by email and phone) and the relevant permit application form.
* I changed "Trust, but verify" to a less idiomatic and more specific title ("Legal limitations of this eRegulations tool"), switched it to dark yellow instead of red (warning instead of error), and made the paragraph slightly smaller than the previous paragraph to help indicate that it's a general disclaimer rather than specifically about this regulation.
* In the sidebar, I repeated the links from the body text and added more contextual support, with sub-headings that break up the list into meaningful chunks. This starts with context about the regulation, then provides additional resources for understanding this regulation, then links to other tools for dealing with this regulation (e-CFR, Federal Register, Regulations.gov).

**Comment by Journerdism** [comment]
Nice! We might consider adding the call in numbers and emails for public comments too. (the people Jen's interviewing right now)

**Comment by cmc333333** [comment]
Cool! Few thoughts

* In general, I'm a little concerned by the sheer number of links on this page. We're intentionally trying to limit the information flood; I think these changes might hurt that. Maybe we can squirrel away more links in expandables
* Probably not worth changing the incompleteness warning for 447, as it'll be gone relatively soon, but we should keep the we-are-verifying template somewhere
* "Trust, but verify" has been one of the mantras of the project -- we may want to keep it for branding's sake alone
* I'm torn on linking to e-CFR in the RHS. Hypothetically, it's just another viewer of the regulation (see also https://www.law.cornell.edu/cfr/text), with fewer bells and whistles.

**Comment by brittag** [comment]
Is there an existing page on the ATF website that explains contact information for public comments? [This page](https://www.atf.gov/rules-and-regulations) seems to just suggest using Regulations.gov.

One easy option for making the page simpler would be to only link each item once, instead of repeating some of the links in the main area and the sidebar. Interestingly, the [current 447 page](https://atf-eregs.18f.gov/447) links to ["Imports and Exports Q&A"](https://www.atf.gov/qa-category/imports-exports) but that doesn't currently contain any material about part 447, so we could remove that link (unless ATF plans to add more there soon).

We could keep "Trust, but verify" and add "Legal limitations of this eRegulations tool" (or similar) as a subheading.

Linking to the e-CFR view could help readers who have these kinds of needs:
* "I want a simple view of this regulation on one page; I don't need the extra bells and whistles right now."
* "I already know how the e-CFR website works and I prefer it since I'm more familiar with it; I don't have time to learn how to use eRegulations right now, but hopefully I can come back later and try this."
* "I don't want to use a beta tool; I'd prefer to use an online source of this regulation that is as official/verified as I can find online."

**Comment by cmc333333** [comment]
> Interestingly, the current 447 page links to "Imports and Exports Q&A" but that doesn't currently contain any material about part 447, so we could remove that link (unless ATF plans to add more there soon).

I think that's more a matter of linking. Consider, for example, the second Q&A references "ATF Form 6A", which is described in part in https://atf-eregs.apps.cloud.gov/447-45/2015-12992#447-45-a-2

> Linking to the e-CFR view could help readers who have these kinds of needs:

I think there's a question here about what kind of context we're expecting from our users. In particular, "how did they arrive at eRegs". If this is the first stop on their regulatory tour, we should definitely mention other interfaces. At the moment, it's much more likely that they found eRegs from an existing introductory page on an agency's website, in which case we probably want to de-emphasize (and declutter) this page by hiding some of this ancillary information.

**Comment by brittag** [comment]
Here's an example of a simpler version that only mentions each link once and omits the general context link (with the wrong styling since it's a "save this page" mockup):

![screen shot 2016-01-11 at 11 21 43 am](https://cloud.githubusercontent.com/assets/391313/12243850/85622b3e-b855-11e5-843e-bedb2cebda16.png)

**Comment by cmc333333** [comment]
@brittag It still feels like a wall of text, hey? I wonder how much can be pulled out into bullets or removed altogether. For example:

* Remove the intro paragraph; it's redundant with the title of the reg
* Move the "scope", "how it relates to other laws", "definitions" into the RHS as fields. These are standard attributes for most any regulations; maybe it makes sense to treat them that way
* Replace the title "This regulation covers topics such as" with something more concise. Maybe "Key Topics" or "Highlights" 
* "What law does this regulation relate to?" is a paragraph which has, at it's core, the name of an act and a link. The rest of the paragraph is superfluous. Maybe just make this a field on the RHS
* Combine "Call" and "Email" links into a "Contact" section with simpler text (e.g. just a phone number and an email address)
* Make "Permit application" a link and remove the superfluous "import firearms..." text

**Comment by jehlers** [comment]
Awesome work so far @brittag! 

A couple of notes :)

>  I also changed this to a dark yellow color (to indicate "warning") instead of red (which often indicates "error").

We don't have a yellow in our palette right now. I'm a little skeptical in moving from red to dark yellow for a few reasons. 1) Dark yellow/orange is hard to find in a "friendly" aka not "brown-ish" color that is 508 compliant against white. 2) I agree with you that, in general, red is more "error" and yellow is more "warning," but we don't really have any error messages in this tool right now. The only time we have a red error message is if we have a time-out issue with loading (which I don't think ATF has needed yet, their regs aren't as long as CFPB's). The red was meant to be a strong warning that caught someone's attention. There is also something about the boldness of the red that feels more authoritative than yellow. Since we are in the process of trying to consolidate styles, I kind of want to wait and see if we have the need for both types of colors. I'll also look into ATF's site, and see if they use any colors that could work here, but I do think that these "warnings" are important enough to warrant red text. 

> I made the human-readable list of contents more detailed and specific, and I linked each subject to the part of the regulation that deals with that subject.

Awesome! I agree with @cmc333333 I think the first 2 bullets you have are unnecessary since they are generally the same format through every regulation. They are useful, but not as helpful in seeing if you are looking at the right regulation for your research purposes.

I also like how you created the new section that relates back to the statute.

Where do you plan those links to go? The munitions list, I think is awesome. Andrew said that a lot of people only visit that list! Are there similar sections that the others can go to? Or would they go to a search results page? Either way, as long as they stay inside the reg, they can be the underlined internal link as opposed to full blue text. I think that will help with some of the "link farm" feeling @cmc333333 is getting. I can also see if there are some new layouts we can use with this new text, if that's helpful. :)

> Is there an existing page on the ATF website that explains contact information for public comments? This page seems to just suggest using Regulations.gov.

I don't think we need to mention anything related to public comments at this stage. These regs are final and haven't changed in a while. When we design the notice and comment stuff and have a current proposal, I think this link and content will come in handy. For regs that are not currently (or recently) in this process, users do not need to be pushed to regs.gov. The FR notices will have all the comments and the intro/guidance information from the last public comment period.

**General comment**
What do you think about moving anything that is additional and may take the user out of the eRegs tool to the sidebar, and leaving everything that takes users inside the reg to various parts (or is directly related to this regulation) inside the main content section? 

That's kind of what this page is doing: http://www.consumerfinance.gov/eregulations/1005 That way we have a distinction between additional / other research you may want to do, and the actual regulation links.

**Comment by brittag** [comment]
Thanks @cmc333333 and @jehlers for these detailed comments, lots to think about! Another mockup and some thoughts:

<img width="1028" alt="screen shot 2016-01-13 at 10 05 30 am" src="https://cloud.githubusercontent.com/assets/391313/12303073/4d890a96-b9dd-11e5-8e46-2ff0b55be6e6.png">

* Each regulation could benefit from a good intro sentence that summarizes the regulation beyond the title. My current placeholder mostly repeats the title as a conservative example, but we could keep that spot for a better intro sentence. I like the way that [this CFPB regulation page](http://www.consumerfinance.gov/eregulations/1002) explains the function of that regulation in a user-centered way. I added a different example as a demonstration.

* I renamed “This regulation covers topics such as” to “Important topics include”, to frame the list as important highlights instead of an alternate table of contents. I removed “scope”, “how it relates to other laws”, and “definitions” from this list since they’re contextual material instead of key topics.

* I changed the internal links to internal-styled links - thanks for pointing that out! I intend them to go the specific part of the regulation that addresses that topic.

* I switched the yellow back to red; it makes sense that this isn’t the right time to make that decision. I like the idea of generally investigating reasonable options for a “warning” style (“caution, you can go ahead and use this, just keep in mind the limitations”) in addition to an “error” style (“stop, something is wrong here”).

* Part of my thinking with the right sidebar is that people often [skim down the left side of body text and skip across briefly to the right](http://www.usability.gov/get-involved/blog/2010/03/eyetracking.html), so putting important information in the right sidebar can risk it not being read. But I’m not sure which pieces of information are most important for these readers, so here's an experiment in putting internal links in the body and external links in the sidebar.

* Potential reasons to keep longer wording and links for contact information, rather than just listing the phone number and email address:
    * Since the ATF has many different phone numbers and email addresses, having specific wording can help people have confidence that they’re calling/emailing the right people.
    * Linking to the contact information allows the centralized contact pages to do any work that ATF thinks should go with phone numbers and email addresses (such as providing a link to an address, customer survey, and “last reviewed” date).

**Comment by cmc333333** [comment]
:+1: I particularly like the distinction between "parts of the regulation" on the left and "other resources which might help you" on the right.

**Comment by brittag** [comment]
We've merged one example landing page for ATF, so I'll close this! We're still working on ideas for the other landing pages.
