### ISSUE TITLE
Test 2 new final rules in the system

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#265]
Test the new 41F final rule and Theft in Transit (Andrew will send over the number for that)

**Comment by Journerdism** [comment]
Here are the two recently published final rules.  Theft in Transit was published on 1-12-16 (81 FR 1307), and NFA Trust 41F was published on 1-15-16 (81 FR 2658).
[NFA Trust Rule - 81 FR 2658 Published 01-15-16.pdf](https://github.com/18F/atf-eregs/files/92225/NFA.Trust.Rule.-.81.FR.2658.Published.01-15-16.pdf)
[Theft Loss Rule - 81 FR 1307 Published 01-12-16.pdf](https://github.com/18F/atf-eregs/files/92226/Theft.Loss.Rule.-.81.FR.1307.Published.01-12-16.pdf)

**Comment by cmc333333** [comment]
https://www.federalregister.gov/articles/2016/01/12/2016-00112/commerce-in-firearms-and-ammunition-reporting-theft-or-loss-of-firearms-in-transit-2007r-9p

and

https://www.federalregister.gov/articles/2016/01/15/2016-00192/machineguns-destructive-devices-and-certain-other-firearms-background-checks-for-responsible-persons

I'm betting we didn't pick these up while parsing most recently because we're using cached results

**Comment by cmc333333** [comment]
Going to add in migration to `cachecontrol` over `requests-cache` as that's part of the reason we didn't see the new data.

**Comment by cmc333333** [comment]
#160 resolves a parsing issue for 2016-00112.

Current issues with 2016-00192
* Missing `In § 479.11, revise the definition for “Person” and add a new definition for the term “Responsible person” to read as follows:`
* Missing `Section 479.90(b) is amended by removing the word “natural” in the third sentence.`
* Although this section is added, it's not been added to the correct subpart: `Section 479.90a is added to subpart F to read as follows.`

**Comment by cmc333333** [comment]
#281, #283, and eregs/fr-notices#1 resolve 2016-00192

**Comment by cmc333333** [comment]
Everything merged!
