### ISSUE TITLE
Design whole part printing

### ISSUE THREAD

**Issue by micahtaylor** [18F/atf-eregs#501]
- [x] Design studio
- [x] Create flow
- [x] Feedback
- [x] Design tweaks off feedback

**Comment by micahtaylor** [comment]
Result from design studio - https://docs.google.com/a/gsa.gov/document/d/1LV_Es5oi09jjZMu79PlQSPwxNiDJ9ocKSjKwB9x8eNg/edit?usp=sharing

**Comment by micahtaylor** [comment]
First pass at an MVP flow. https://gsa.invisionapp.com/share/A3CZORCDK#/248139610_Subpart_with_print_link

**Comment by micahtaylor** [comment]
User flow
Screen 1: user is on a section (or a part's landing page, or search results within a section)
user clicks the print icon in the heading
Screen 2:  user is taken to a display of the full part; JS automatically opens a print dialog
user exits the print dialog (via canceling or sending the job to a printer)
Screen 3: user is sees the full part of the reg. there's an extra link to allow printing the whole part (in case they missed that dialog box)

**Comment by micahtaylor** [comment]
An element that has come up during some research is that it would be nice when printing to have a list of related documents at the end of the print document.

**Comment by micahtaylor** [comment]
Another option for screen 1 print action placement on the subpart.
<img width="264" alt="expanded 1" src="https://user-images.githubusercontent.com/671894/29213359-8778e4d2-7e68-11e7-906c-5128802fcb8e.png">
<img width="264" alt="collapsed sidebar no related 1" src="https://user-images.githubusercontent.com/671894/29213358-87764df8-7e68-11e7-97ec-64509456d045.png">

**Comment by micahtaylor** [comment]
Possibly clearer to add dynamic content to print title.

<img width="264" alt="expanded 2" src="https://user-images.githubusercontent.com/671894/29213519-377381bc-7e69-11e7-9f43-6dfa328f04d4.png">
<img width="264" alt="collapsed sidebar no related 2" src="https://user-images.githubusercontent.com/671894/29213520-3775f0aa-7e69-11e7-91f0-6cd22cd6acb3.png">

**Comment by carodew** [comment]
I like the last option you posted best. 🎉  It also gives us flexibility if we discover that users need a more obvious way to print subparts or other things. 

Do you think making it look so similar to the other headings (that expand sections) will confuse users into thinking it's an expand-type interaction as well?

**Comment by micahtaylor** [comment]
Agreed. I don't think it will be confusing as the headers are now taking on various functional roles now.

**Comment by carodew** [comment]
I had written this out in #503 without realizing we already had an issue, transferring here – 


As someone who doesn't know how to print or create a PDF from their browser, I want to be able to print the entire text of a CFR part.

## acceptance criteria

- Users can find how to print or create a PDF of an entire CFR part from the UI, even if they don't know how to do it with my browser (this could be a print button, or it could be unobtrusive instructions, or something else)
The output should include a clear h1 level heading for the CFR part (e.g. "27 CFR Part 555") on the first page
The output should include URL to the first subpart of the CFR part. (Note – this is what I suspect would be the best user experience since our working theory is that seeing the part broken down into smaller sections is better than seeing the whole thing at once, but this could be entirely wrong. The other option would be to provide the URL to the view of the entire thing).

**Comment by micahtaylor** [comment]
Seems that we have come to an ideal and, as the righthand sidebar will have a higher prescient, an MVP for full page printing. 
Closing as the design is done. A new issue can be open for implementation.
