### ISSUE TITLE
Help text for "Effective date"

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#510]
> Add “?” next to “Effective Date” in ribbon to click for generic explanation of what the “effective date” means.

The specific implementation doesn't matter so much as the explanation.

**Comment by carodew** [comment]
Where did this request come from? I know we had a little bit of confusion about effective date but I'm not sure how widespread it is.

**Comment by carodew** [comment]
Answered – both a little bit from user research and ATF request.

**Comment by carodew** [comment]
Serendipitously, we got into previous versions in the usability test this morning (user was particular interested in it). It gave me some ideas for ways we could address the confusion that a lot of people seem to have.

**Comment by carodew** [comment]
Some notes/thoughts – 

We may be able to clarify the effective date by just changing the wording a little, and we seem to have space for it. It could say something like "The current regulation has been in effect since 7/22/2016" for the current regulation and "This version of the regulation was in effect from 6/13/2016 to 7/22/2016." for past regulations?

When navigating to a previous version of a regulation, it's not very apparent that you're in a different time mode, because the effective date is pretty low in the visual hierarchy. However it feels important to draw more attention to it. Maybe we shift the color of the effective date bar (to yellow or something that calls attention), and supplement that with some type of icon for colorblind users? Happy to create some mock ups although today is painfully full of meetings, so it might end up waiting until Micah gets back anyway.

**Comment by carodew** [comment]
Wireframey renderings of one idea for treating effective date (would still need to pass through visual design) – 

![current reg](https://user-images.githubusercontent.com/10144074/29470097-0a99157a-8419-11e7-9f09-5fa73d727e60.png)
![past regulation](https://user-images.githubusercontent.com/10144074/29470098-0a9f07b4-8419-11e7-9c56-a09038450f39.png)

**Comment by micahtaylor** [comment]
@carodew Just so I'm clear the 1st is the current version of the reg and the second is the previous, correct. Also, I'm seeing a style treatment intent in the current subpart/effective date banner. Is that also a desired part of the change?

**Comment by carodew** [comment]
"the 1st is the current version of the reg and the second is the previous" - yep!

"style treatment intent in the current subpart/effective date banner" – this is my lo fi mock up, and not intended to suggest a visual direction or change to the current visual style, only a change to wording in the effective date bit. 

I am suggesting a style change for the previous version screen, but doesn't necessarily have to be exactly like this. I think we need to more aggressively indicate that a user is looking at a previous version and not the current, so I am suggesting a color change (as well as adding an icon for color blind users). I picked yellow because I do think it should serve as kind of an alert for the user, but am open to other options. I want people to be able to tell at a glance, without reading anything, that something is different about this screen and that they should pay attention.

**Comment by micahtaylor** [comment]
Design updates. 

![localhost-8000-478-100-2016-12100](https://user-images.githubusercontent.com/671894/29795941-3c95ff2c-8c14-11e7-87d6-6cc07d823b02.png)


![localhost-8000-478-100-2016-00112](https://user-images.githubusercontent.com/671894/29795863-b2a06294-8c13-11e7-9cac-9cccf9ed45bc.png)

Was working in https://github.com/18F/atf-eregs/tree/510-effective-date but encountering limitations to my knowledge of the best way to implement.
